{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a12371a1-b304-4201-98b7-23fe386913fc",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-11-27 11:45:12.103 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:12.105 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.190 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\imran\\AppData\\Roaming\\Python\\Python312\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-11-27 11:45:13.193 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.195 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.202 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.217 Session state does not function when running a script without `streamlit run`\n",
      "2025-11-27 11:45:13.218 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.219 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.224 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.224 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.226 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.228 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.230 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.232 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.232 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.234 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.236 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.236 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.237 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.237 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.238 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.239 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.240 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.242 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.243 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.244 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.245 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.246 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.246 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.248 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.250 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.251 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.252 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.253 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.254 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.255 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.257 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.258 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.259 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.259 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.260 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.261 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.262 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.263 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.265 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.265 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.267 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.268 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.269 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.270 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.270 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.271 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-27 11:45:13.271 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pdfplumber\n",
    "import pandas as pd\n",
    "import io\n",
    "import re\n",
    "\n",
    "# --- App Configuration ---\n",
    "st.set_page_config(page_title=\"Student KSB Mapper\", layout=\"wide\")\n",
    "\n",
    "st.title(\"🎓 Student Assignment Mapper\")\n",
    "st.markdown(\"\"\"\n",
    "This tool scans your **Main Document** for specific **KSB references** \n",
    "and generates a mapping matrix automatically.\n",
    "\"\"\")\n",
    "\n",
    "# --- Sidebar: Inputs ---\n",
    "st.sidebar.header(\"1. Project Details\")\n",
    "unit_name = st.sidebar.text_input(\"Unit Name/Code\", placeholder=\"e.g. Unit 5 - Leadership\")\n",
    "doc_title = st.sidebar.text_input(\"Document Title\", placeholder=\"e.g. Portfolio Submission\")\n",
    "\n",
    "st.sidebar.header(\"2. Define KSBs\")\n",
    "st.sidebar.info(\"Enter the KSBs you want to search for (one per line).\")\n",
    "ksb_input_raw = st.sidebar.text_area(\"KSB List\", placeholder=\"K1\\nK2\\nS1\\nS4\\nB1\")\n",
    "\n",
    "# Process KSB list into a clean list\n",
    "ksb_list = [x.strip() for x in ksb_input_raw.split('\\n') if x.strip()]\n",
    "\n",
    "st.sidebar.header(\"3. Upload Document\")\n",
    "uploaded_file = st.sidebar.file_uploader(\"Upload Main Document (PDF only)\", type=['pdf'])\n",
    "\n",
    "# --- Logic Functions ---\n",
    "def extract_mappings(file, search_terms):\n",
    "    results = []\n",
    "    with pdfplumber.open(file) as pdf:\n",
    "        total_pages = len(pdf.pages)\n",
    "        progress_bar = st.progress(0)\n",
    "\n",
    "        for i, page in enumerate(pdf.pages):\n",
    "            page_num = i + 1\n",
    "            text = page.extract_text()\n",
    "\n",
    "            if text:\n",
    "                for term in search_terms:\n",
    "                    pattern = r'\\b' + re.escape(term) + r'\\b'\n",
    "                    if re.search(pattern, text, re.IGNORECASE):\n",
    "                        results.append({\n",
    "                            \"Unit\": unit_name,\n",
    "                            \"Title\": doc_title,\n",
    "                            \"KSB Reference\": term,\n",
    "                            \"Page Number\": page_num\n",
    "                        })\n",
    "\n",
    "            progress_bar.progress((i + 1) / total_pages)\n",
    "\n",
    "    return results\n",
    "\n",
    "# --- Main Execution ---\n",
    "if st.button(\"Generate Mapping Document\", type=\"primary\"):\n",
    "    if not uploaded_file:\n",
    "        st.error(\"Please upload a Main Document PDF.\")\n",
    "    elif not ksb_list:\n",
    "        st.error(\"Please enter at least one KSB to search for.\")\n",
    "    else:\n",
    "        with st.spinner(\"Scanning document...\"):\n",
    "            try:\n",
    "                uploaded_file.seek(0)\n",
    "                mappings = extract_mappings(uploaded_file, ksb_list)\n",
    "\n",
    "                if mappings:\n",
    "                    df = pd.DataFrame(mappings)\n",
    "                    df = df.sort_values(by=['KSB Reference', 'Page Number'])\n",
    "\n",
    "                    st.success(f\"Found {len(df)} matches!\")\n",
    "                    st.dataframe(df, use_container_width=True)\n",
    "\n",
    "                    output = io.BytesIO()\n",
    "                    with pd.ExcelWriter(output, engine='openpyxl') as writer:\n",
    "                        df.to_excel(writer, index=False, sheet_name='Mapping')\n",
    "\n",
    "                    st.download_button(\n",
    "                        label=\"📥 Download Mapping (.xlsx)\",\n",
    "                        data=output.getvalue(),\n",
    "                        file_name=\"KSB_Mapping_Document.xlsx\",\n",
    "                        mime=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\"\n",
    "                    )\n",
    "                else:\n",
    "                    st.warning(\"No KSBs found in the document. Check your spelling or file content.\")\n",
    "\n",
    "            except Exception as e:\n",
    "                st.error(f\"An error occurred: {e}\")\n",
    "\n",
    "# --- Instructions Footer ---\n",
    "st.markdown(\"---\")\n",
    "st.markdown(\"### How to use this app:\")\n",
    "st.markdown(\"\"\"\n",
    "1. **Enter Details:** Type the Unit and Title on the left.\n",
    "2. **List KSBs:** Paste your specific KSB codes (e.g., `K5`, `S12`) on the left.\n",
    "3. **Upload:** Drag and drop your assignment/thesis PDF.\n",
    "4. **Generate:** Click the button to scan the PDF. The app will look for the exact text of your KSBs and tell you which page they are on.\n",
    "\"\"\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "13a2f3ce-da9a-4571-a99c-d612782fa9f4",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
